"""
Modelos de base de datos (SQLAlchemy)
"""

from app.models.song import Song
# ESTÁ IMPORTANDO EL MODELO SONG DESDE EL MODULO SONG.PY, ESTO NOS PERMITE QUE OTROS MODULOS OUEDAN IMPORTAN DONG ESCRIBIENDO APP.MODELS, EN VEZ DE ESCRIBIR APP.MODELS.APP.SONG
__all__ = ["Song"] # CUANDO ESCRIBAMOS EN OTRO ARCHIVO APP.MODELS IMPORT, AUTOMATICAMENTE NOS SALDRÁ SONG.